// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRK4YWof38sSKm9wp3hi0agBTGov-ayBw',
    appId: '1:629602509914:web:c52f9b57fdbf07e8432463',
    messagingSenderId: '629602509914',
    projectId: 'meuappflutter-firebase',
    authDomain: 'meuappflutter-firebase.firebaseapp.com',
    storageBucket: 'meuappflutter-firebase.firebasestorage.app',
    measurementId: 'G-139XFW1N09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAwIerNAQ-pC2PLfRl3jkQ-XqBwDnA-4',
    appId: '1:629602509914:android:079a6d44b18626e5432463',
    messagingSenderId: '629602509914',
    projectId: 'meuappflutter-firebase',
    storageBucket: 'meuappflutter-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9t6-ZzkAVmA0QfIhPm7J7DQn2NTF5blQ',
    appId: '1:629602509914:ios:1a277625cdc15356432463',
    messagingSenderId: '629602509914',
    projectId: 'meuappflutter-firebase',
    storageBucket: 'meuappflutter-firebase.firebasestorage.app',
    iosBundleId: 'com.angelachantal.app.meuappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9t6-ZzkAVmA0QfIhPm7J7DQn2NTF5blQ',
    appId: '1:629602509914:ios:1a277625cdc15356432463',
    messagingSenderId: '629602509914',
    projectId: 'meuappflutter-firebase',
    storageBucket: 'meuappflutter-firebase.firebasestorage.app',
    iosBundleId: 'com.angelachantal.app.meuappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRK4YWof38sSKm9wp3hi0agBTGov-ayBw',
    appId: '1:629602509914:web:d67f44a9248167e8432463',
    messagingSenderId: '629602509914',
    projectId: 'meuappflutter-firebase',
    authDomain: 'meuappflutter-firebase.firebaseapp.com',
    storageBucket: 'meuappflutter-firebase.firebasestorage.app',
    measurementId: 'G-T95LW1DTXV',
  );

}